select (5 + 5) / 72 * 15 as res;

SELECT CEILING(12.333332323) AS RESULTADO; 
SELECT FLOOR(12.333332323) AS RESULTADO; 
SELECT ROUND(12.49) AS RESULTADO; 

SELECT RAND() AS RESULTADO;

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE * PRECO,2) AS FATURAMENTO
FROM itens_notas_fiscais;

SELECT * FROM itens_notas_fiscais;

SELECT YEAR(DATA_VENDA), FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);