SELECT LTRIM('   OLÁ') AS RESULTADO;
SELECT RTRIM('OLÁ    ') AS RESULTADO;
SELECT TRIM('   OLÁ   ') AS RESULTADO;
SELECT CONCAT('Olá,',' ', 'Tudo bem', '?') AS RESULTADO;
SELECT UPPER('olá, tudo bem?') as resultado;
SELECT SUBSTRING('Olá, tudo bem?', 6,4) AS RESULTADO;
SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM tabela_de_clientes;
SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO) AS COMPLETO
FROM tabela_de_clientes;
SELECT CURDATE() AS RESULTADO;
SELECT current_timestamp() AS RESULTADO;
SELECT DATEDIFF(CURRENT_TIMESTAMP(), '1991-07-15') AS RESULTADO;

SELECT DISTINCT DATA_VENDA FROM notas_fiscais;

SELECT DISTINCT DATA_VENDA,
DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES,
YEAR(DATA_VENDA) AS ANO FROM notas_fiscais;

SELECT NOME, TIMESTAMPDIFF (YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS    IDADE
FROM  tabela_de_clientes;